apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-nodeport-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
    name: http
  selector:
    app: employees
